### ISSUE TITLE
option to build all icons

### ISSUE THREAD

**Issue by cgatian** [fabiospampinato/icon-font-buildr#6]
Provide an option to allow building all icons based off the sources provided. 

This should be doable with the API. If that's the perferred approach then please close 😄

**Comment by fabiospampinato** [comment]
> Provide an option to allow building all icons based off the sources provided.

That can't really work, if your source is `https://foo.com/[icon].svg` how are we supposed to retrieve all icons?

I think it'd be better just to have a separate configuration for this use case 🤔 We could add support for globs for local sources though, but I think that'd make the library harder to understand for not much upside.

**Comment by cgatian** [comment]
Good point. I was thinking since we are globing a local folder the input/output is redundant. Perhaps an option use `localFileNames`? Again, not a big deal I accomplished this using the API.

**Comment by fabiospampinato** [comment]
I'll think about it, but I feel that using the API for this would be more appropriate.
