### ISSUE TITLE
Generate stylesheets

### ISSUE THREAD

**Issue by ZanyMonk** [fabiospampinato/icon-font-buildr#9]
It would be nice to implement automatic stylesheets generation so icon-font-buildr integrates nicely into a building pipeline, for hot-reloading for example.

Do you plan on implementing this in a near future ?
Are you open to PRs ?

Nice project you have here :)

**Comment by fabiospampinato** [comment]
I'd consider that a bit out of scope, but I can see the usefulness of that in some cases.

What do you think the API should look like for this?

**Comment by ZanyMonk** [comment]
We can expose a `getIconsStylesheet()` function, which would render and return a simple EJS template based on the generated codepoints and a few options (class prefix, CSS/SCSS/custom template).
The generated file would contain:
- a `@font-face` at-rule
- a class definition that applies the font-face
- a class definition for each icon that applies the corresponding codepoint

Maybe some other lib should do this job ? You tell me.

**Comment by fabiospampinato** [comment]
Yeah maybe it's better to have this logic separate from the library.
